apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  loadBalancerIP: None
  ports:
    - port: 4040
      protocol: TCP
      targetPort: 4040
  selector:
    app: api-deployment