apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api-deployment
          image: gcr.io/foodlocal-218406/api:latest
          ports:
            - containerPort: 4040
              name: api-deployment
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: NODE_ENV
            - name: MONGODB_PORT_PROD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: MONGODB_PORT_PROD
            - name: MONGODB_HOST_PROD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: MONGODB_HOST_PROD
            - name: MONGODB_DBNAME_PROD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: MONGODB_DBNAME_PROD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: JWT_SECRET
            - name: REPLICA_SET_NAME_PROD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: REPLICA_SET_NAME_PROD