image: docker

services:
  - docker:dind
  
stages:
 - build

build:
  stage: build
  script:
    - apk add --no-cache py-pip      # <--
    - pip install docker-compose     # <--
    - docker-compose up --build