apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.207.121.66
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4040
  selector:
    app: api-deployment