# not working yet
version: '3'
services:
  api:
    build:
      context: ./API
      dockerfile: DockerfileLocal
    container_name: "api_foodlocal"
    ports:
      - "4040:4040" # Expose ports [HOST:CONTAINER}
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: DockerfileLocal
    container_name: "frontend_foodlocal"
    ports:
      - "3000:3000"
    depends_on:
      - api
