apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: ingress
 annotations:
  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: foodlocal.ch
    http:
      paths:
      - path: /api
        backend:
          serviceName: api-service
          servicePort: 4040
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 80
