apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: foodlocal-crt
spec:
  secretName: foodlocal-crt
  commonName: foodlocal.ch
  dnsNames:
  - www.foodlocal.ch
  - foodlocal.ch
  - api.foodlocal.ch
  - www.api.foodlocal.ch
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - foodlocal.ch
      - www.foodlocal.ch
      - api.foodlocal.ch
      - www.api.foodlocal.ch
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer