version: '3'
services:
  gce:
    env_file: ./.env
    image: gce_kubectl:latest
    build:
      context: .
      args:
        - GC_CLUSTER_ID=${GC_CLUSTER_ID}
        - GC_ZONE=${GC_ZONE}
        - GC_PROJECT_ID=${GC_PROJECT_ID}
