# not working yet
version: '3'
services:
  gce:
    env_file: ./.env
    container_name: "gce"
    build:
      image: gce_kubectl
      args:
        - GC_CLUSTER_ID=${GC_CLUSTER_ID}
        - GC_ZONE=${GC_ZONE}
        - GC_PROJECT_ID=${GC_PROJECT_ID}