# not working yet
version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    ports:
      - "4040:4040" # Expose ports [HOST:CONTAINER}
      - "27016:27017"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27017:27017"